# Generated by Django 6.0.7 on 2026-08-18 17:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSetting',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Sozlama kaliti')),
                ('value', models.TextField(verbose_name='Qiymat')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Tavsif')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Billing sozlamasi',
                'verbose_name_plural': 'Billing sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Oylik obuna', max_length=100, verbose_name='Obuna nomi')),
                ('duration_days', models.PositiveIntegerField(default=30, verbose_name='Davomiyligi (kun)')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), max_digits=14, verbose_name='Narxi (UZS)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Obuna rejasi',
                'verbose_name_plural': 'Obuna rejalari',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Balans summasi (UZS)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O‘zgartirilgan vaqt')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Balans',
                'verbose_name_plural': 'Balanslar',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='To‘lov ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('100.00'))], verbose_name='To‘lov summasi (UZS)')),
                ('payment_method', models.CharField(choices=[('CLICK', 'Click'), ('PAYME', 'Payme'), ('TRANSFER', 'Transfer (Bank o‘tkazmasi)')], max_length=20, verbose_name='To‘lov usuli')),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('COMPLETED', 'Muvaffaqiyatli to‘landi'), ('FAILED', 'To‘lov amalga oshmadi'), ('CANCELLED', 'Bekor qilindi')], default='PENDING', max_length=20, verbose_name='To‘lov holati')),
                ('provider_transaction_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Provider tranzaksiya ID (Click / Payme)')),
                ('proof_image', models.FileField(blank=True, null=True, upload_to='payments/proofs/', verbose_name='Bank cheki rasmi / hujjati')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin izohi (tasdiqlash yoki rad etish sababi)')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Qo‘shimcha parametrlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='To‘langan vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'To‘lov',
                'verbose_name_plural': 'To‘lovlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Promokod')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='Beriladigan balans summasi (UZS)')),
                ('activation_limit', models.PositiveIntegerField(default=1, verbose_name='Maksimal aktivatsiyalar soni')),
                ('activations_count', models.PositiveIntegerField(default=0, verbose_name='Ishlatilgan aktivatsiyalar soni')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Amal qilish boshlanishi')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Amal qilish muddati (tugash sanasi)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promo_codes', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan admin')),
            ],
            options={
                'verbose_name': 'Promokod',
                'verbose_name_plural': 'Promokodlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateTimeField(verbose_name='Tugash sanasi')),
                ('status', models.CharField(choices=[('ACTIVE', 'Faol'), ('EXPIRED', 'Muddati tugagan'), ('CANCELLED', 'Bekor qilingan')], default='ACTIVE', max_length=20, verbose_name='Holat')),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='To‘langan narx (UZS)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_subscriptions', to='billing.subscriptionplan', verbose_name='Obuna rejasi')),
            ],
            options={
                'verbose_name': 'Obuna',
                'verbose_name_plural': 'Obunalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Balance to‘ldirildi'), ('TEST_PURCHASE', 'Test sotib olindi'), ('SUBSCRIPTION', 'Subscription sotib olindi'), ('REGISTRATION_BONUS', 'Registration bonus'), ('PROMO_CODE', 'Promo code faollashtirildi'), ('ADMIN_CREDIT', 'Admin tomonidan to‘ldirildi'), ('ADMIN_DEBIT', 'Admin tomonidan yechildi'), ('REFUND', 'To‘lov qaytarildi')], max_length=30, verbose_name='Tranzaksiya turi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Summa (UZS)')),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Oldingi balans')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Keyingi balans')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('status', models.CharField(choices=[('SUCCESS', 'Muvaffaqiyatli'), ('PENDING', 'Kutilmoqda'), ('FAILED', 'Xatolik yuz berdi'), ('CANCELLED', 'Bekor qilindi')], default='SUCCESS', max_length=20, verbose_name='Holat')),
                ('reference_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bog‘liq ID (Payment/Purchase/Promo/Admin)')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name="Qo‘shimcha ma'lumotlar")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Amal bajarilgan vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Tranzaksiya',
                'verbose_name_plural': 'Tranzaksiyalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoCodeActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Olingan summa (UZS)')),
                ('activated_at', models.DateTimeField(auto_now_add=True, verbose_name='Faollashtirilgan vaqt')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='billing.promocode', verbose_name='Promokod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_code_activations', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Promokod faollashtiruvi',
                'verbose_name_plural': 'Promokod faollashtiruvlari',
                'ordering': ['-activated_at'],
                'unique_together': {('promo_code', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.PositiveBigIntegerField(db_index=True, verbose_name='Test ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='To‘langan narx (UZS)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sotib olingan vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Test xaridi',
                'verbose_name_plural': 'Test xaridlari',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'test_id')},
            },
        ),
    ]
