# Generated by Django 6.0.7 on 2026-08-11 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Savol matni')),
                ('passage', models.TextField(blank=True, null=True, verbose_name='Matn (Reading uchun matn)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/images/', verbose_name='Savol rasmi')),
                ('audio', models.FileField(blank=True, null=True, upload_to='questions/audio/', verbose_name='Listening audiosi')),
                ('question_type', models.CharField(choices=[('SINGLE_CHOICE', "Bitta to'g'ri javobli"), ('MULTIPLE_CHOICE', "Bir nechta to'g'ri javobli"), ('TEXT_ANSWER', 'Matnli javob (Writing)'), ('AUDIO_ANSWER', 'Ovozli javob (Speaking)')], default='SINGLE_CHOICE', max_length=30, verbose_name='Savol turi')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='Ball')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Variant matni')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri javobmi?")),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='tests.question', verbose_name='Savol')),
            ],
            options={
                'verbose_name': 'Javob varianti',
                'verbose_name_plural': 'Javob variantlari',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Test nomi')),
                ('description', models.TextField(blank=True, verbose_name='Test haqida tavsif')),
                ('category', models.CharField(choices=[('IELTS', 'IELTS'), ('SAT', 'SAT'), ('MILLIY_SERTIFIKAT', 'Milliy Sertifikat'), ('LANGUAGES', 'Tillar'), ('DTM', 'DTM Testlari'), ('TOPIC_BASED', 'Mavzulashtirilgan Testlar')], default='IELTS', max_length=50, verbose_name='Kategoriya')),
                ('subcategory', models.CharField(blank=True, help_text='Masalan: Full Mock, Reading, Math, 9-sinf Tarix 1-mavzu...', max_length=100, verbose_name="Ichki yo'nalish / Subkategoriya")),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Vaqt (daqiqa)')),
                ('is_published', models.BooleanField(default=False, verbose_name='Nashr qilinganmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tests', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi (Content Manager / Admin)')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Testlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.test', verbose_name='Tegishli test'),
        ),
        migrations.CreateModel(
            name='UserTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, verbose_name='Natija balli (Band / SAT score / %)')),
                ('correct_count', models.PositiveIntegerField(default=0, verbose_name="To'g'ri javoblar soni")),
                ('incorrect_count', models.PositiveIntegerField(default=0, verbose_name="Noto'g'ri javoblar soni")),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='Jami savollar soni')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Topshirilgan vaqt')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_results', to='tests.test', verbose_name='Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Test Natijasi',
                'verbose_name_plural': 'Test Natijalari',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, null=True, verbose_name='Yozma javob')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri bajarildimi?")),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.question', verbose_name='Savol')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.answer', verbose_name='Tanlangan variant')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_breakdown', to='tests.usertestresult', verbose_name='Natija')),
            ],
            options={
                'verbose_name': 'Savol natijasi tafsiloti',
                'verbose_name_plural': 'Savollar natijasi tafsilotlari',
            },
        ),
    ]
