# Generated by Django 6.0.7 on 2026-08-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='0.00 = bepul test', max_digits=12, verbose_name="Test narxi (so'm)"),
        ),
        migrations.AddField(
            model_name='usertestresult',
            name='time_spent_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='Sarflangan vaqt (soniya)'),
        ),
    ]
