# Generated by Django 6.1 on 2026-08-10 21:05

import apps.authentication.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLoginCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telegram_id', models.BigIntegerField(db_index=True)),
                ('telegram_first_name', models.CharField(blank=True, default='', max_length=255)),
                ('telegram_photo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('code', models.CharField(default=apps.authentication.models.generate_6_digit_code, max_length=6)),
                ('attempts', models.IntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Telegram Login Code',
                'verbose_name_plural': 'Telegram Login Codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
